"""Apply generated content layers to the BPMN model JSON.

All functions mutate the model in-place (shapes lists) or return new shapes
to be appended to model["childShapes"].

Shape IDs for generated content always start with BA_SID ("sid-BA-") so
clean_ba_content() can remove them precisely.
"""
from .constants import BA_SID, LANE_COLOR_PALETTE

# ── Badge numbering constants ─────────────────────────────────────────────────
_BADGE_SIZE   = 22        # px, square — compact corner badge
_BADGE_OFFSET = 11        # center badge on the task's top-left corner
_BADGE_COLOR  = "#1473e8" # SAP/Signavio blue


# ── Task documentation ────────────────────────────────────────────────────────

def apply_task_docs(shapes: list, task_docs: dict) -> None:
    """Write generated documentation to task properties (recursive).

    Only writes if the task has no existing documentation or if the existing
    documentation was previously generated by the annotator ([BA] prefix).
    Human-authored docs are never overwritten.
    """
    for s in shapes:
        rid = s.get("resourceId", "")
        if s.get("stencil", {}).get("id") == "Task" and rid in task_docs:
            existing = s.get("properties", {}).get("documentation", "")
            if not existing or existing.startswith("[BA]"):
                s["properties"]["documentation"] = task_docs[rid]
        apply_task_docs(s.get("childShapes", []), task_docs)


# ── Department color coding ───────────────────────────────────────────────────

def assign_lane_colors(parsed: dict) -> dict:
    """Return {lane_id: color_dict} cycling through LANE_COLOR_PALETTE."""
    return {
        lane["id"]: LANE_COLOR_PALETTE[i % len(LANE_COLOR_PALETTE)]
        for i, lane in enumerate(parsed["lanes"])
    }


def apply_colors(shapes: list, lane_colors: dict) -> None:
    """Apply department color coding to tasks based on their parent lane (recursive)."""
    for s in shapes:
        rid = s.get("resourceId", "")
        if s.get("stencil", {}).get("id") == "Lane" and rid in lane_colors:
            colors = lane_colors[rid]
            for child in s.get("childShapes", []):
                if child.get("stencil", {}).get("id") == "Task":
                    child["properties"]["bgcolor"]     = colors["bgcolor"]
                    child["properties"]["bordercolor"] = colors["bordercolor"]
        apply_colors(s.get("childShapes", []), lane_colors)


# ── TextAnnotation builder ────────────────────────────────────────────────────

def _make_annotation(annot_id: str, text: str,
                     x: float, y: float,
                     width: float, height: float) -> dict:
    """Build a Signavio TextAnnotation shape dict."""
    return {
        "resourceId": annot_id,
        "properties": {"text": text},
        "stencil":    {"id": "TextAnnotation"},
        "childShapes": [],
        "outgoing":   [],
        "bounds": {
            "upperLeft":  {"x": x,         "y": y},
            "lowerRight": {"x": x + width, "y": y + height},
        },
        "dockers": [],
    }


# ── Lane summaries ────────────────────────────────────────────────────────────

def build_lane_summaries(parsed: dict, lane_summaries: dict) -> list:
    """Return TextAnnotation shapes for lane summaries, placed right of the pool.

    Positioning: x = pool_right + 20, y = lane abs_y + 5.
    Height adapts to lane height (capped at 220, min 100).
    """
    pb = parsed.get("pool_bounds")
    if not pb:
        return []
    pool_right = pb["lowerRight"]["x"]
    annots = []
    for lane in parsed["lanes"]:
        text = lane_summaries.get(lane["id"], "")
        if not text:
            continue
        safe_id = lane["id"].replace("sid-", "").replace("-", "_")
        annot_h = min(220, max(100, lane["height"] - 10))
        annots.append(_make_annotation(
            f"{BA_SID}LANE-{safe_id}", text,
            x=pool_right + 20, y=lane["abs_y"] + 5,
            width=290, height=annot_h,
        ))
    return annots


# ── Impact analysis ───────────────────────────────────────────────────────────

def build_impact_analysis(parsed: dict, impact_text: str):
    """Return a TextAnnotation shape for the impact analysis, placed below the pool.

    Returns None if pool_bounds is unavailable or impact_text is empty.
    """
    pb = parsed.get("pool_bounds")
    if not pb or not impact_text:
        return None
    pool_width = pb["lowerRight"]["x"] - pb["upperLeft"]["x"]
    return _make_annotation(
        f"{BA_SID}IMPACT", impact_text,
        x=pb["upperLeft"]["x"], y=pb["lowerRight"]["y"] + 20,
        width=pool_width, height=280,
    )


# ── Gateway annotations ───────────────────────────────────────────────────────

def build_gateway_annotations(parsed: dict, gateway_texts: dict) -> list:
    """Return TextAnnotation shapes placed above each gateway with a routing note."""
    pb = parsed.get("pool_bounds")
    if not pb:
        return []
    pool_ul = pb["upperLeft"]
    annots  = []
    for gw in parsed["gateways"]:
        text = gateway_texts.get(gw["id"], "")
        if not text:
            continue
        lane = next((l for l in parsed["lanes"] if l["id"] == gw["lane_id"]), None)
        lane_abs_y = lane["abs_y"] if lane else pool_ul["y"]
        gw_abs_x   = pool_ul["x"] + gw["bounds_local"]["x"]
        gw_abs_y   = lane_abs_y   + gw["bounds_local"]["y"]
        safe_id    = gw["id"].replace("sid-", "").replace("-", "_")
        annots.append(_make_annotation(
            f"{BA_SID}GW-{safe_id}", text,
            x=gw_abs_x - 20, y=max(pool_ul["y"] + 5, gw_abs_y - 68),
            width=200, height=58,
        ))
    return annots


# ── Phase headers ─────────────────────────────────────────────────────────────

def build_phase_headers(parsed: dict, phase_headers: list) -> list:
    """Return TextAnnotation shapes placed above the pool as phase labels.

    Each phase header is positioned above the first task of that phase.
    """
    pb = parsed.get("pool_bounds")
    if not pb or not phase_headers:
        return []
    pool_ul   = pb["upperLeft"]
    task_map  = {t["id"]: t for t in parsed["tasks"]}
    annots    = []
    for i, ph in enumerate(phase_headers):
        ref_task = task_map.get(ph.get("ref_task_id", ""))
        if not ref_task:
            continue
        phase_abs_x = pool_ul["x"] + ref_task["bounds_local"]["x"]
        annots.append(_make_annotation(
            f"{BA_SID}PHASE-{i}", ph.get("label", ""),
            x=phase_abs_x - 10, y=pool_ul["y"] - 55,
            width=170, height=40,
        ))
    return annots


# ── Task auto-numbering ───────────────────────────────────────────────────────

# Prefix used in the OLD text-prefix style (kept for migration stripping)
_NUM_PREFIX = "[BA#]"


def number_tasks(shapes: list, parsed: dict) -> None:
    """Ensure task labels are clean (no text-prefix numbering).

    The old style ([BA#] N. Task name) is stripped here.
    Visual badge numbering is handled separately by build_number_badges().
    Call both together to get clean labels + numbered corner badges.
    """
    strip_task_numbers(shapes)


def build_number_badges(model: dict, parsed: dict) -> list:
    """Create numbered badge annotations at the top-left corner of each task.

    Badges are compact 22x22 TextAnnotation shapes positioned to slightly
    overlap the task's top-left corner.  They carry the step number (1-based,
    left-to-right reading order) and are styled with a blue background.

    All badge resource IDs start with BA_SID so clean_ba_content() removes
    them automatically on clean / rerun operations.

    SPM rendering note
    ------------------
    Signavio Process Manager does not expose a native circle primitive via
    its REST API outside of BPMN event stencils.  Badges are rendered as
    small compact TextAnnotation boxes (22x22 px) at the task corner.  The
    bgcolor / bordercolor properties are set to SAP blue; whether SPM renders
    the coloured background depends on its TextAnnotation stencil definition.
    At 22px the box reads as a compact corner badge in the diagram.
    """
    # ── Build absolute top-left position for every task ───────────────────────
    task_abs: dict = {}
    for top in model.get("childShapes", []):
        if top.get("stencil", {}).get("id") != "Pool":
            continue
        px = top["bounds"]["upperLeft"]["x"]
        py = top["bounds"]["upperLeft"]["y"]
        for lane in top.get("childShapes", []):
            if lane.get("stencil", {}).get("id") != "Lane":
                continue
            lx = lane["bounds"]["upperLeft"]["x"]
            ly = lane["bounds"]["upperLeft"]["y"]
            for elem in lane.get("childShapes", []):
                if elem.get("stencil", {}).get("id") != "Task":
                    continue
                b = elem["bounds"]["upperLeft"]
                task_abs[elem["resourceId"]] = {
                    "x": px + lx + b["x"],
                    "y": py + ly + b["y"],
                }

    # ── Order tasks left-to-right, top-to-bottom (same as old number_tasks) ──
    pb = parsed.get("pool_bounds")
    pool_ul_x = pb["upperLeft"]["x"] if pb else 0
    lane_abs_y_map = {l["id"]: l["abs_y"] for l in parsed["lanes"]}
    ordered = sorted(
        parsed["tasks"],
        key=lambda t: (
            pool_ul_x + t["bounds_local"]["x"],
            lane_abs_y_map.get(t["lane_id"], 0) + t["bounds_local"]["y"],
        ),
    )

    # ── Emit one badge per task ───────────────────────────────────────────────
    badges = []
    for i, task in enumerate(ordered, start=1):
        pos = task_abs.get(task["id"])
        if not pos:
            continue
        bx = pos["x"] - _BADGE_OFFSET
        by = pos["y"] - _BADGE_OFFSET
        safe = task["id"].replace("sid-", "").replace("-", "_")[:20]
        badges.append({
            "resourceId": f"{BA_SID}BADGE-{safe}",
            "properties": {
                "text":        str(i),
                "bgcolor":     _BADGE_COLOR,
                "bordercolor": _BADGE_COLOR,
            },
            "stencil":    {"id": "TextAnnotation"},
            "childShapes": [],
            "outgoing":   [],
            "bounds": {
                "upperLeft":  {"x": bx,               "y": by},
                "lowerRight": {"x": bx + _BADGE_SIZE, "y": by + _BADGE_SIZE},
            },
            "dockers": [],
        })
    return badges


def strip_task_numbers(shapes: list) -> None:
    """Remove annotator-applied task numbers (reverse of the old number_tasks).

    Strips the '[BA#] N. ' prefix from task name properties.
    Called by clean_ba_content indirectly — or directly in clean_only mode.
    """
    _strip_numbers(shapes)


def _strip_numbers(shapes: list) -> None:
    """Recursively strip [BA#] number prefixes from task names."""
    import re
    _pattern = re.compile(r"^\[BA#\]\s+\d+\.\s+")
    for s in shapes:
        if s.get("stencil", {}).get("id") == "Task":
            name = s.get("properties", {}).get("name", "")
            s["properties"]["name"] = _pattern.sub("", name)
        _strip_numbers(s.get("childShapes", []))


# ── Sequence flow labels ──────────────────────────────────────────────────────

def apply_flow_labels(shapes: list, flow_labels: dict) -> None:
    """Write generated labels to unlabeled sequence flows (recursive)."""
    for s in shapes:
        rid = s.get("resourceId", "")
        if s.get("stencil", {}).get("id") == "SequenceFlow" and rid in flow_labels:
            existing = s.get("properties", {}).get("name", "")
            if not existing or existing.startswith("[BA]"):
                s["properties"]["name"] = flow_labels[rid]
        apply_flow_labels(s.get("childShapes", []), flow_labels)
