"""Remove [BA]-generated content from a BPMN model.

The cleaner identifies annotator content by two markers:
  1. Shape resourceId starts with "sid-BA-"  (all TextAnnotation shapes)
  2. Text/doc property starts with "[BA]"    (task docs, flow labels)

Also removes legacy test annotation IDs (sid-ANNOT-*) created by earlier
prototype code that pre-dated the sid-BA- naming convention.

Human-authored content (anything without these markers) is never touched.
"""
from .constants import BA_PREFIX, BA_SID

# Legacy IDs from prototype/test code — cleaned alongside sid-BA-* shapes
_LEGACY_PREFIXES = ("sid-ANNOT-",)


def _is_ba_shape(shape: dict) -> bool:
    """Return True if this shape was generated by the BPMN Annotator."""
    rid  = shape.get("resourceId", "")
    text = shape.get("properties", {}).get("text", "")
    return (
        rid.startswith(BA_SID)
        or any(rid.startswith(p) for p in _LEGACY_PREFIXES)
        or text.startswith(BA_PREFIX)
    )


def clean_ba_content(shapes: list) -> list:
    """Recursively remove all [BA]-generated shapes and annotations.

    Specifically:
      - Removes TextAnnotation shapes with sid-BA-* IDs
      - Clears task documentation that starts with [BA]
      - Clears sequence flow labels that start with [BA]
      - Removes BA outgoing references from task shapes

    Returns the cleaned list (suitable for model["childShapes"]).
    """
    cleaned = []
    for s in shapes:
        if _is_ba_shape(s):
            continue

        stencil = s.get("stencil", {}).get("id", "")

        # Clear BA-generated task documentation
        if stencil == "Task":
            doc = s.get("properties", {}).get("documentation", "")
            if doc.startswith(BA_PREFIX):
                s["properties"]["documentation"] = ""
            # Remove BA outgoing associations
            s["outgoing"] = [
                o for o in s.get("outgoing", [])
                if not o.get("resourceId", "").startswith(BA_SID)
            ]

        # Clear BA-generated sequence flow labels
        if stencil == "SequenceFlow":
            name = s.get("properties", {}).get("name", "")
            if name.startswith(BA_PREFIX):
                s["properties"]["name"] = ""

        # Recurse into children (e.g. tasks inside lanes inside pools)
        s["childShapes"] = clean_ba_content(s.get("childShapes", []))
        cleaned.append(s)

    return cleaned


def has_ba_content(model: dict) -> bool:
    """Return True if the model already contains [BA]-annotator content.

    Useful to warn the user before overwriting or offer clean_and_rerun.
    """
    def _check(shapes: list) -> bool:
        for s in shapes:
            if _is_ba_shape(s):
                return True
            if s.get("stencil", {}).get("id") == "Task":
                doc = s.get("properties", {}).get("documentation", "")
                if doc.startswith(BA_PREFIX):
                    return True
            if _check(s.get("childShapes", [])):
                return True
        return False

    return _check(model.get("childShapes", []))
